# -*- coding: utf-8 -*-
"""Creacion de Gafetes
 
Automatically generated by Colab.
 
Original file is located at
    https://colab.research.google.com/drive/1Relv1KktW6FkdEA1VKHtRaGsddRsK0U8
 
1.Limpieza del entorno y archivos CSV.
 
2.Descarga de competidores y PRs.
 
3.Pivot de resultados.
 
4.Conversión de centisegundos a formato legible.
 
5.Orden final por nombre alfabéticamente.
"""

# ============================
# Auto-instalación de dependencias (si es necesario)
# ============================
import sys
import subprocess

def install_package(package):
    """Instala un paquete usando pip"""
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", package])
    except subprocess.CalledProcessError as e:
        print(f"Error al instalar {package}: {e}")
        print("Por favor, instálelo manualmente: pip install", package)
        sys.exit(1)

# Lista de paquetes requeridos: {nombre_de_importación: nombre_en_pip}
required_packages = {
    'requests': 'requests',
    'pandas': 'pandas',
    'reportlab': 'reportlab',
    'PyPDF2': 'PyPDF2',
    'fitz': 'pymupdf'  # importamos fitz pero el paquete se llama pymupdf
}

# Verificar e instalar paquetes faltantes
for import_name, package_name in required_packages.items():
    try:
        __import__(import_name)
    except ImportError:
        print(f"Paquete '{package_name}' no encontrado. Instalando...")
        install_package(package_name)

# ============================
# Script completo: genera gafetes usando la plantilla y limpia temporales
# ============================
import os, glob, time, unicodedata
import requests
import pandas as pd
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from PyPDF2 import PdfReader, PdfWriter
import fitz  # pymupdf
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# Registro automático de fuentes locales y del sistema
FONTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fonts")
FUENTE_ROL_DEFAULT = "Helvetica-Bold"

# 1. Cargar fuentes locales de alta calidad si existen
font_files = {
    "BebasNeue": os.path.join(FONTS_DIR, "BebasNeue.ttf"),
    "Montserrat-Bold": os.path.join(FONTS_DIR, "Montserrat-Bold.ttf"),
    "Oswald-Bold": os.path.join(FONTS_DIR, "Oswald-Bold.ttf"),
    "Teko-Bold": os.path.join(FONTS_DIR, "Teko-Bold.ttf"),
    "RussoOne": os.path.join(FONTS_DIR, "RussoOne.ttf"),
}
for fname, fpath in font_files.items():
    if os.path.exists(fpath):
        try:
            pdfmetrics.registerFont(TTFont(fname, fpath))
            if fname == "BebasNeue":
                FUENTE_ROL_DEFAULT = "BebasNeue"
        except Exception:
            pass

# 2. Si no hay locales, buscar en sistema
if FUENTE_ROL_DEFAULT == "Helvetica-Bold":
    for sys_font in ["C:/Windows/Fonts/impact.ttf", "C:/Windows/Fonts/trebucbd.ttf"]:
        if os.path.exists(sys_font):
            try:
                name = "Impact" if "impact" in sys_font.lower() else "Trebuchet-Bold"
                pdfmetrics.registerFont(TTFont(name, sys_font))
                FUENTE_ROL_DEFAULT = name
                break
            except Exception:
                pass

# ---------- Config ----------
TEMPLATE = "Plantilla Gafete.pdf"               # asegúrate de subirla

# 1. Recuadro automático de Records Personales
DIBUJAR_CUADRO_RECORDS = True       # True: genera el recuadro gris redondeado translúcido desde código
OPACIDAD_CUADRO = 0.60              # Transparencia del fondo (0.0 = transparente, 1.0 = opaco)
COLOR_CUADRO = (0.85, 0.85, 0.85)   # Color RGB del recuadro (gris claro translúcido)
BORDE_CUADRO = True                 # Dibuja un borde sutil
OPACIDAD_BORDE = 0.25               # Transparencia del borde
COLOR_BORDE = (1.0, 1.0, 1.0)       # Color RGB del borde (blanco)
RADIO_ESQUINAS = 12                 # Curvatura de esquinas en puntos (pt)

# 2. Línea horizontal separadora
DIBUJAR_LINEA_SEPARADORA = True     # True: dibuja la línea entre el nombre y el rol
COLOR_LINEA = (0.12, 0.12, 0.12)    # Color RGB de la línea
GROSOR_LINEA = 1.0                  # Grosor de la línea en puntos (pt)

# 3. Texto del Rol (ej. COMPETIDOR, ORGANIZADOR, DELEGADO)
DIBUJAR_TEXTO_ROL = True            # True: dibuja el rol centrado debajo de la línea
TEXTO_ROL_DEFAULT = "COMPETIDOR"    # Texto por defecto
FUENTE_ROL = FUENTE_ROL_DEFAULT     # Opciones: "BebasNeue", "Montserrat-Bold", "Oswald-Bold", "Teko-Bold", "RussoOne", "Helvetica-Bold"
TAMANO_FUENTE_ROL = 14.5 if FUENTE_ROL_DEFAULT == "BebasNeue" else 11.0  # Tamaño de fuente del rol
COLOR_ROL = (0.08, 0.08, 0.08)      # Color del texto del rol
ROLES_PERSONALIZADOS = {            # Diccionario opcional de roles por WCA ID: {"2023ESPI07": "COMPETIDOR", ...}
    # "2018ABCD01": "ORGANIZADOR",
    # "2015XYZW02": "DELEGADO WCA",
}

# Solicitar competition_id al usuario
print("\n" + "="*50)
print(" CONFIGURACIÓN DE COMPETICIÓN WCA ")
print("="*50)
print("Ejemplos de competition_id: DelacuestaXmas2025, WublinOpen2024, etc.")
competition_id = input("Ingrese el competition_id de la WCA: ").strip()

if not competition_id:
    print("Error: Debe ingresar un competition_id válido.")
    sys.exit(1)

OUTPUT_PDF = f"gafetes_final_{competition_id}.pdf"

print(f"\nCompetencia seleccionada: {competition_id}")
print("="*50 + "\n")

BASE_API = "https://www.worldcubeassociation.org/api/v0"
REGS_URL = f"{BASE_API}/competitions/{competition_id}/registrations"
USER_URL = f"{BASE_API}/users/{{}}"
PERSON_URL = f"{BASE_API}/persons/{{}}"

# ---------- Limpieza inicial ----------
for f in glob.glob("*.pdf"):
    if os.path.basename(f) != TEMPLATE:
        try:
            os.remove(f)
        except:
            pass
for f in glob.glob("*.csv"):
    try: os.remove(f)
    except: pass

print("[OK] Carpeta limpia (se preserva la plantilla).")

# ---------- 0. Comprobaciones ----------
if not os.path.exists(TEMPLATE):
    raise FileNotFoundError(f"No encontré {TEMPLATE} en el directorio actual. Súbelo antes de ejecutar.")

# Verificar que la competencia exista antes de continuar
print("Verificando acceso a la competencia...")
try:
    test_resp = requests.get(REGS_URL, timeout=10)
    test_resp.raise_for_status()
    test_data = test_resp.json()
    if not test_data:
        print(f"Advertencia: No se encontraron registros para la competencia '{competition_id}'")
    else:
        print(f"[OK] Acceso confirmado a la competencia '{competition_id}' ({len(test_data)} registros encontrados)")
except requests.exceptions.RequestException as e:
    print(f"Error al acceder a la competencia '{competition_id}': {e}")
    print("Verifica que el competition_id sea correcto y que tengas conexión a internet.")
    sys.exit(1)

# ---------- 1. Descargar registros ----------
print("Descargando registros de la competencia...")
resp = requests.get(REGS_URL)
resp.raise_for_status()
registrations = resp.json()
print(f"Registros encontrados: {len(registrations)}")

# ---------- 2. Info de competidores ----------
competitors = []
for r in registrations:
    user_id = r.get("user_id")
    events = r.get("event_ids", []) or []
    ru = requests.get(USER_URL.format(user_id))
    if ru.status_code != 200:
        continue
    user = ru.json().get("user", {})
    competitors.append({
        "user_id": user_id,
        "name": user.get("name"),
        "wca_id": user.get("wca_id"),
        "country": user.get("country_iso2"),
        "events": events
    })
    time.sleep(0.08)

# Ordenar alfabéticamente por nombre (ignorando tildes)
competitors.sort(key=lambda c: unicodedata.normalize("NFD", (c["name"] or "").lower()))
print(f"[OK] Competidores ordenados: {[c['name'] for c in competitors[:5]]}...")

df_competitors = pd.DataFrame(competitors)
# df_competitors.to_csv("competencia_competitors.csv", index=False, encoding="utf-8-sig")
# print("[OK] competencia_competitors.csv guardado.")

# ---------- 3. Descargar PRs ----------
prs_rows = []
for comp in competitors:
    wid = comp["wca_id"]
    if not wid:
        continue
    rp = requests.get(PERSON_URL.format(wid))
    if rp.status_code != 200:
        continue
    pjson = rp.json()
    personal = pjson.get("personal_records", {})
    for ev in comp["events"]:
        rec = personal.get(ev, {})
        if not rec:
            continue
        prs_rows.append({
            "wca_id": wid,
            "name": comp["name"],
            "event": ev,
            "single": rec.get("single", {}).get("best"),
            "average": rec.get("average", {}).get("best")
        })
    time.sleep(0.08)

df_prs = pd.DataFrame(prs_rows)
# df_prs.to_csv("competencia_prs.csv", index=False, encoding="utf-8-sig")
# print("[OK] competencia_prs.csv guardado.")

# ---------- 4. Formatear resultados ----------

def format_cs(cs):
    if pd.isna(cs) or cs == "" or cs == 0:
        return ""
    cs = int(cs)

    sec = cs // 100
    cs_rem = cs % 100
    mins = sec // 60
    sec = sec % 60

    if mins > 0:
        return f"{mins}:{sec:02d}.{cs_rem:02d}"
    else:
        return f"{sec}.{cs_rem:02d}"


def format_mbf(val):
    """Formatea el tiempo de 3x3 Multi-Blind"""
    if pd.isna(val) or val == "" or val == 0:
        return ""
    val = int(val)
    val_str = str(val)
    
    # El formato WCA para 333mbf:
    # El formato "new" es: 0DDTTTTTMM (10 dígitos)
    # difference = 99 - DD
    # timeInSeconds = TTTTT (5 dígitos)
    # missed = MM
    # solved = difference + missed
    # attempted = solved + missed
    
    # Pero la API puede devolver valores con diferente longitud
    # Ajustar según la longitud
    if len(val_str) == 9:
        # Formato sin el 0 inicial
        DD = int(val_str[:2])
        TTTTT = int(val_str[2:7])
        MM = int(val_str[7:])
    elif len(val_str) == 10:
        DD = int(val_str[1:3])
        TTTTT = int(val_str[3:8])
        MM = int(val_str[8:])
    else:
        #other lengths - try to handle generically
        DD = int(val_str[:2])
        MM = int(val_str[-2:])
        TTTTT = int(val_str[2:-2])
    
    difference = 99 - DD
    missed = MM
    solved = difference + missed
    attempted = solved + missed
    time_seconds = TTTTT
    
    if time_seconds == 99999:
        if solved > 0:
            return f"{solved}/{attempted}"
        else:
            return ""
    
    mins = time_seconds // 60
    secs = time_seconds % 60
    
    if mins > 0:
        time_str = f"{mins}:{secs:02d}"
    else:
        time_str = f"{secs}"
    
    if solved > 0:
        return f"{solved}/{attempted} {time_str}"
    else:
        return ""
    val = int(val)
    val_str = str(val)
    
    # El formato de WCA puede ser "old" (9 dígitos) o "new" (10 dígitos)
    # Primero intentamos con formato "old": 1SSAATTTTT
    # solved = 99 - SS
    # attempted = AA
    # timeInSeconds = TTTTT
    
    if len(val_str) == 9:
        # Formato old sin el 1 inicial o con otro dígito
        # Intentamos parsear directamente
        # Estructura: SSAATTTTT (9 dígitos)
        if len(val_str) >= 9:
            try:
                # Para valores como 970075800:
                # Podría ser: SS=97, AA=00, TTTTT=75800
                SS = int(val_str[0:2])
                AA = int(val_str[2:4])
                TTTTT = int(val_str[4:9])
                
                solved = 99 - SS
                attempted = AA
                time_seconds = TTTTT
                
                # Verificar si los valores son razonables
                # attempted debe ser <= 99 y solved <= attempted
                if attempted > 0 and attempted <= 99 and solved <= attempted:
                    if time_seconds <= 99999:
                        mins = time_seconds // 60
                        secs = time_seconds % 60
                        
                        if mins > 0:
                            time_str = f"{mins}:{secs:02d}"
                        else:
                            time_str = f"{secs}"
                        
                        if solved > 0:
                            return f"{solved}/{attempted} {time_str}"
            except:
                pass
    
    # Si el formato old no funcionó, intentamos con formato new: 0DDTTTTTMM
    val_str = val_str.zfill(10)
    
    DD = int(val_str[:2])
    TTTTT = int(val_str[2:7])
    MM = int(val_str[7:])
    
    difference = 99 - DD
    missed = MM
    solved = difference + missed
    attempted = solved + missed
    time_seconds = TTTTT
    
    if time_seconds == 99999:
        if solved > 0:
            return f"{solved}/{attempted}"
        else:
            return ""
    
    time_seconds = TTTTT
    mins = time_seconds // 60
    secs = time_seconds % 60
    
    if mins > 0:
        time_str = f"{mins}:{secs:02d}"
    else:
        time_str = f"{secs}"
    
    if solved > 0:
        return f"{solved}/{attempted} {time_str}"
    else:
        return ""


# 🔴 NORMALIZACIÓN REAL DE FEWEST MOVES
def normalize_fm(val):
    if pd.isna(val) or val == "" or val == 0:
        return None

    val = float(val)

    # Caso 0.27 → 27
    if val < 1:
        return val * 100

    # Caso 2700 → 27
    if val >= 100:
        return val / 100

    # Caso 27 → 27
    return val


def format_fm(val, is_average=False):
    moves = normalize_fm(val)
    if moves is None:
        return ""

    if is_average:
        return f"{moves:.2f}".rstrip("0").rstrip(".")
    else:
        return str(int(round(moves)))


def format_by_event(row, field):
    if row["event"] == "333fm":
        return format_fm(row[field], is_average=(field == "average"))
    elif row["event"] == "333mbf":
        return format_mbf(row[field])
    else:
        return format_cs(row[field])


df_prs["single_f"] = df_prs.apply(lambda r: format_by_event(r, "single"), axis=1)
df_prs["average_f"] = df_prs.apply(lambda r: format_by_event(r, "average"), axis=1)


# ---------- 5. Dimensiones plantilla ----------
tpl_reader = PdfReader(TEMPLATE)
tpl_page = tpl_reader.pages[0]
TPL_W = float(tpl_page.mediabox.width)
TPL_H = float(tpl_page.mediabox.height)

# ---------- 6. Nombres oficiales y orden WCA ----------
WCA_EVENT_ORDER = [
    "333", "222", "444", "555", "666", "777",
    "333bf", "333fm", "333oh", "clock", "minx",
    "pyram", "skewb", "sq1", "444bf", "555bf", "333mbf"
]

event_names_long = {
    "222": "2x2", "333": "3x3", "444": "4x4", "555": "5x5", "666": "6x6", "777": "7x7",
    "333bf": "3x3 Blindfolded", "333fm": "3x3 Fewest Moves", "333oh": "3x3 One-Handed",
    "clock": "Clock", "minx": "Megaminx", "pyram": "Pyraminx", "skewb": "Skewb",
    "sq1": "Square-1", "444bf": "4x4 Blindfolded", "555bf": "5x5 Blindfolded",
    "333mbf": "3x3 Multi-Blind"
}

event_names_short = {
    "222": "2x2", "333": "3x3", "444": "4x4", "555": "5x5", "666": "6x6", "777": "7x7",
    "333bf": "3BLD", "333fm": "FMC", "333oh": "3x3 OH", "clock": "Clock", "minx": "Megaminx",
    "pyram": "Pyraminx", "skewb": "Skewb", "sq1": "Square-1", "444bf": "4BLD", "555bf": "5BLD",
    "333mbf": "MBLD"
}

# ---------- 7. Crear gafetes individuales ----------
print("Generando gafetes individuales usando la plantilla...")

# Carpeta temporal para gafetes individuales (se elimina al final)
TEMP_DIR = "_gafetes_temp"
os.makedirs(TEMP_DIR, exist_ok=True)

# Caché de banderas: descarga cada país solo una vez
from io import BytesIO
from reportlab.lib.utils import ImageReader
flag_cache = {}

def get_flag(country_code):
    if not country_code or len(country_code) != 2:
        return None
    cc = country_code.lower()
    if cc in flag_cache:
        return flag_cache[cc]
    try:
        resp = requests.get(f"https://flagcdn.com/w80/{cc}.png", timeout=5)
        if resp.status_code == 200:
            flag_cache[cc] = ImageReader(BytesIO(resp.content))
            return flag_cache[cc]
    except:
        pass
    flag_cache[cc] = None
    return None

final_gafetes = []
for idx, comp in enumerate(competitors):
    wid = comp["wca_id"]
    country_code = comp.get("country")
    competitor_name = comp["name"] or str(comp["user_id"])
    
    # Obtener bandera desde caché (descarga solo si no está cacheada)
    flag_image = get_flag(country_code)
    
    dfc = df_prs[df_prs["wca_id"] == wid] if wid else pd.DataFrame()

    overlay = os.path.join(TEMP_DIR, f"overlay_{idx:03d}.pdf")
    c = canvas.Canvas(overlay, pagesize=(TPL_W, TPL_H))

    # ========================================================
    # Recuadro redondeado translúcido para los Records (Opcional)
    # ========================================================
    if DIBUJAR_CUADRO_RECORDS:
        c.saveState()
        c.setFillAlpha(OPACIDAD_CUADRO)
        c.setFillColorRGB(*COLOR_CUADRO)
        if BORDE_CUADRO:
            c.setStrokeAlpha(OPACIDAD_BORDE)
            c.setStrokeColorRGB(*COLOR_BORDE)
            stroke_flag = 1
        else:
            c.setStrokeAlpha(0)
            stroke_flag = 0
        
        box_x = 12
        box_y = 18
        box_w = TPL_W - 24
        box_h = 114
        c.roundRect(box_x, box_y, box_w, box_h, RADIO_ESQUINAS, fill=1, stroke=stroke_flag)
        c.restoreState()

    # ======================
    # Ajustes de posiciones
    # ======================
    box_top = 18 + 114 - 11.5  # Posición del título dentro del recuadro bajado

    # ===== Nombre del competidor (con ajuste automático de tamaño para nombres largos) =====
    name_font_size = 12.0
    flag_width = 0.8 * cm
    flag_height = 0.53 * cm
    max_name_width = TPL_W - (flag_width + 0.8 * cm if flag_image else 1.0 * cm)
    
    while name_font_size > 7.5 and c.stringWidth(competitor_name, "Helvetica-Bold", name_font_size) > max_name_width:
        name_font_size -= 0.5

    c.setFont("Helvetica-Bold", name_font_size)
    name_width = c.stringWidth(competitor_name, "Helvetica-Bold", name_font_size)

    if flag_image:
        center_x = TPL_W / 2
        total_width = flag_width + 0.3 * cm + name_width
        start_x = center_x - total_width / 2
        c.drawImage(flag_image, start_x, TPL_H - 4.2 * cm, width=flag_width, height=flag_height, mask='auto')
        c.drawString(start_x + flag_width + 0.3 * cm, TPL_H - 4.1 * cm, competitor_name)
    else:
        c.drawCentredString(TPL_W / 2, TPL_H - 4.1 * cm, competitor_name)

    # ===== Línea horizontal separadora (Opcional) =====
    if DIBUJAR_LINEA_SEPARADORA:
        c.saveState()
        c.setStrokeColorRGB(*COLOR_LINEA)
        c.setLineWidth(GROSOR_LINEA)
        c.line(22, TPL_H - 4.45 * cm, TPL_W - 22, TPL_H - 4.45 * cm)
        c.restoreState()

    # ===== Texto del Rol del participante (Opcional) =====
    if DIBUJAR_TEXTO_ROL:
        c.saveState()
        c.setFont(FUENTE_ROL, TAMANO_FUENTE_ROL)
        c.setFillColorRGB(*COLOR_ROL)
        rol_text = ROLES_PERSONALIZADOS.get(wid, TEXTO_ROL_DEFAULT)
        c.drawCentredString(TPL_W / 2, TPL_H - 4.95 * cm, rol_text)
        c.restoreState()

    # ----- Título Records Personales -----
    c.setFont("Helvetica-Bold", 9.5)
    title = "Records Personales (Single,Average):"
    title_width = c.stringWidth(title, "Helvetica-Bold", 9.5)
    c.drawString((TPL_W - title_width) / 2, box_top, title)

    # Convertir a lista y ordenar según el orden oficial WCA
    events_list = dfc.to_dict('records')
    events_list.sort(key=lambda x: WCA_EVENT_ORDER.index(x['event']) if x['event'] in WCA_EVENT_ORDER else 99)
    num_events = len(events_list)

    if num_events == 0:
        # Debutante sin PRs aún registrados
        c.setFont("Helvetica-Oblique", 9)
        c.setFillColorRGB(0.2, 0.2, 0.2)
        debut_msg = "Primer Torneo Oficial WCA"
        dm_width = c.stringWidth(debut_msg, "Helvetica-Oblique", 9)
        c.drawString((TPL_W - dm_width) / 2, box_top - 26, debut_msg)
        c.setFillColorRGB(0, 0, 0)
    elif num_events <= 7:
        # Distribución en 1 columna centrada
        font_size = 8.5 if num_events <= 4 else 8.0
        line_spacing = 13.0 if num_events <= 4 else 11.0
        y_start = box_top - 18.0
        c.setFont("Helvetica", font_size)
        
        for i, ev_data in enumerate(events_list):
            ev = ev_data["event"]
            ev_name = event_names_long.get(ev, ev)
            s = ev_data["single_f"]
            a = ev_data["average_f"]
            line = f"{ev_name}: {s}" + (f" / {a}" if a else "")
            y = y_start - i * line_spacing
            c.drawCentredString(TPL_W / 2, y, line)
    else:
        # Distribución en 2 columnas balanceadas
        split = (num_events + 1) // 2
        if split <= 6:
            font_size = 7.5
            line_spacing = 10.5
        elif split <= 8:
            font_size = 7.0
            line_spacing = 9.2
        else:
            font_size = 6.5
            line_spacing = 8.5
        
        y_start = box_top - 17.0
        col_centers = [box_x + box_w * 0.25, box_x + box_w * 0.75]
        
        c.setFont("Helvetica", font_size)
        for i, ev_data in enumerate(events_list):
            col = 0 if i < split else 1
            row = i if i < split else i - split
            ev = ev_data["event"]
            ev_name = event_names_short.get(ev, ev)
            s = ev_data["single_f"]
            a = ev_data["average_f"]
            line = f"{ev_name}: {s}" + (f" / {a}" if a else "")
            
            y = y_start - row * line_spacing
            c.drawCentredString(col_centers[col], y, line)

    c.save()
    # Superponer overlay en plantilla
    tpl_r = PdfReader(TEMPLATE)
    ov_r = PdfReader(overlay)
    base_page = tpl_r.pages[0]
    base_page.merge_page(ov_r.pages[0])
    writer = PdfWriter()
    writer.add_page(base_page)

    final_name = os.path.join(TEMP_DIR, f"gafete_final_{idx:03d}.pdf")
    with open(final_name, "wb") as fh:
        writer.write(fh)

    os.remove(overlay)
    final_gafetes.append(final_name)

print(f"[OK] Gafetes individuales creados: {len(final_gafetes)}")


# ---------- 7b. Gafetes de reserva (relleno de páginas incompletas) ----------
GAFETES_POR_PAGINA = 6
total = len(final_gafetes)
resto = total % GAFETES_POR_PAGINA

print("\n" + "="*50)
print(" GAFETES DE RESERVA ")
print("="*50)

def crear_gafete_en_blanco(idx_reserva):
    """Genera un gafete en blanco (solo plantilla, sin texto) para reserva."""
    tpl_r = PdfReader(TEMPLATE)
    writer = PdfWriter()
    writer.add_page(tpl_r.pages[0])
    nombre = os.path.join(TEMP_DIR, f"gafete_reserva_{idx_reserva}.pdf")
    with open(nombre, "wb") as fh:
        writer.write(fh)
    return nombre

gafetes_reserva_creados = []

if resto == 0:
    # Caso 1: múltiplo exacto de 6 → preguntar si quiere página extra de reserva
    print(f"Los {total} competidores llenan exactamente {total // GAFETES_POR_PAGINA} página(s) (sin espacios sobrantes).")
    print(f"¿Desea agregar una página extra con {GAFETES_POR_PAGINA} gafetes en blanco de reserva?")
    print("  [1] Sí, agregar página de reserva")
    print("  [2] No, el PDF queda exacto")
    opcion = input("Seleccione una opción (1/2): ").strip()
    if opcion == "1":
        for i in range(GAFETES_POR_PAGINA):
            gafetes_reserva_creados.append(crear_gafete_en_blanco(i))
        print(f"[OK] Se agregarán {GAFETES_POR_PAGINA} gafetes de reserva en una página extra.")
    else:
        print("[OK] Sin gafetes de reserva. El PDF quedará exacto.")
else:
    # Caso 2: última página incompleta → preguntar si quiere rellenar los huecos
    faltantes = GAFETES_POR_PAGINA - resto
    paginas_completas = total // GAFETES_POR_PAGINA
    print(f"Hay {total} competidores → {paginas_completas} página(s) completa(s) + 1 página con solo {resto} gafete(s).")
    print(f"Faltan {faltantes} gafete(s) para completar la última página.")
    print(f"¿Qué desea hacer con los {faltantes} espacio(s) sobrante(s)?")
    print(f"  [1] Rellenar con {faltantes} gafete(s) de reserva (recomendado)")
    print(f"  [2] Dejar los espacios en blanco")
    opcion = input("Seleccione una opción (1/2): ").strip()
    if opcion == "1":
        for i in range(faltantes):
            gafetes_reserva_creados.append(crear_gafete_en_blanco(i))
        print(f"[OK] Se agregarán {faltantes} gafete(s) de reserva para completar la última página.")
    else:
        print("[OK] Los espacios sobrantes quedarán vacíos.")

# Agregar gafetes de reserva al final de la lista
final_gafetes.extend(gafetes_reserva_creados)

if gafetes_reserva_creados:
    print(f"[OK] Total de gafetes a imprimir: {len(final_gafetes)} ({len(gafetes_reserva_creados)} de reserva)")
print("="*50 + "\n")


# ---------- 8. Combinar en tamaño Carta (6 por página, 2x3, rotados, con márgenes mínimos) ----------
print("Combinando gafetes en tamaño Carta (6 por página, márgenes mínimos)...")

# Tamaño carta
PAGE_W = 21.59 * cm   # 8.5 pulgadas
PAGE_H = 27.94 * cm   # 11 pulgadas

# Márgenes reducidos y separación mínima
MARGIN_LEFT = 0.4 * cm
MARGIN_TOP = 0.4 * cm
GAP_X = 0.5 * cm
GAP_Y = 0.5 * cm

# Escala ajustada para llenar más la hoja
SCALE = 0.97
GAF_W = TPL_H * SCALE
GAF_H = TPL_W * SCALE

# Posiciones (2 columnas x 3 filas)
NUM_COLS = 2
NUM_ROWS = 3
x_positions = [MARGIN_LEFT, MARGIN_LEFT + GAF_W + GAP_X]
y_positions = [
    PAGE_H - MARGIN_TOP - GAF_H,
    PAGE_H - MARGIN_TOP - 2*GAF_H - GAP_Y,
    PAGE_H - MARGIN_TOP - 3*GAF_H - 2*GAP_Y
]

# Crear PDF final
doc = fitz.open()

for i in range(0, len(final_gafetes), 6):
    page = doc.new_page(width=PAGE_W, height=PAGE_H)
    group = final_gafetes[i:i + 6]

    for j, gafpath in enumerate(group):
        col = j % NUM_COLS
        row = j // NUM_COLS

        x = x_positions[col]
        y = y_positions[row]
        rect = fitz.Rect(x, y, x + GAF_W, y + GAF_H)

        gaf_doc = fitz.open(gafpath)
        # Mantener alta calidad y orientación correcta (rotar 90°)
        page.show_pdf_page(rect, gaf_doc, 0, rotate=90)

        gaf_doc.close()

if os.path.exists(OUTPUT_PDF):
    try:
        os.remove(OUTPUT_PDF)
    except:
        pass
import tempfile
import shutil

# Save to temp file first, then move
temp_file = OUTPUT_PDF + ".temp"
doc.save(temp_file)
doc.close()

# Remove old file and rename temp
if os.path.exists(OUTPUT_PDF):
    try:
        os.remove(OUTPUT_PDF)
    except:
        pass

shutil.move(temp_file, OUTPUT_PDF)
print(f"[OK] PDF final listo y ajustado: {OUTPUT_PDF}")




# ---------- 9. Limpiar temporales ----------
import shutil as _shutil
try:
    _shutil.rmtree(TEMP_DIR)
except:
    pass

print("[OK] Archivos temporales eliminados. Solo quedan la plantilla y el PDF final.")