# -*- coding: utf-8 -*-
"""Creacion de Gafetes
 
Automatically generated by Colab.
 
Original file is located at
    https://colab.research.google.com/drive/1Relv1KktW6FkdEA1VKHtRaGsddRsK0U8
 
1.Limpieza del entorno y archivos CSV.
 
2.Descarga de competidores y PRs.
 
3.Pivot de resultados.
 
4.Conversión de centisegundos a formato legible.
 
5.Orden final por nombre alfabéticamente.
"""

# ============================
# Auto-instalación de dependencias (si es necesario)
# ============================
import sys
import subprocess

def install_package(package):
    """Instala un paquete usando pip"""
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", package])
    except subprocess.CalledProcessError as e:
        print(f"Error al instalar {package}: {e}")
        print("Por favor, instálelo manualmente: pip install", package)
        sys.exit(1)

# Lista de paquetes requeridos: {nombre_de_importación: nombre_en_pip}
required_packages = {
    'requests': 'requests',
    'pandas': 'pandas',
    'reportlab': 'reportlab',
    'PyPDF2': 'PyPDF2',
    'fitz': 'pymupdf'  # importamos fitz pero el paquete se llama pymupdf
}

# Verificar e instalar paquetes faltantes
for import_name, package_name in required_packages.items():
    try:
        __import__(import_name)
    except ImportError:
        print(f"Paquete '{package_name}' no encontrado. Instalando...")
        install_package(package_name)

# ============================
# Script completo: genera gafetes usando la plantilla y limpia temporales
# ============================
import os, glob, time, unicodedata
import requests
import pandas as pd
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from PyPDF2 import PdfReader, PdfWriter
import fitz  # pymupdf

# ---------- Config ----------
TEMPLATE = "Plantilla Gafete.pdf"               # asegúrate de subirla
# OUTPUT_PDF se definirá después de obtener el competition_id

# Solicitar competition_id al usuario
print("\n" + "="*50)
print(" CONFIGURACIÓN DE COMPETICIÓN WCA ")
print("="*50)
print("Ejemplos de competition_id: DelacuestaXmas2025, WublinOpen2024, etc.")
competition_id = input("Ingrese el competition_id de la WCA: ").strip()

if not competition_id:
    print("Error: Debe ingresar un competition_id válido.")
    sys.exit(1)

OUTPUT_PDF = f"gafetes_final_{competition_id}.pdf"

print(f"\nCompetencia seleccionada: {competition_id}")
print("="*50 + "\n")

BASE_API = "https://www.worldcubeassociation.org/api/v0"
REGS_URL = f"{BASE_API}/competitions/{competition_id}/registrations"
USER_URL = f"{BASE_API}/users/{{}}"
PERSON_URL = f"{BASE_API}/persons/{{}}"

# ---------- Limpieza inicial ----------
for f in glob.glob("*.pdf"):
    if os.path.basename(f) != TEMPLATE:
        try:
            os.remove(f)
        except:
            pass
for f in glob.glob("*.csv"):
    try: os.remove(f)
    except: pass

print("[OK] Carpeta limpia (se preserva la plantilla).")

# ---------- 0. Comprobaciones ----------
if not os.path.exists(TEMPLATE):
    raise FileNotFoundError(f"No encontré {TEMPLATE} en el directorio actual. Súbelo antes de ejecutar.")

# Verificar que la competencia exista antes de continuar
print("Verificando acceso a la competencia...")
try:
    test_resp = requests.get(REGS_URL, timeout=10)
    test_resp.raise_for_status()
    test_data = test_resp.json()
    if not test_data:
        print(f"Advertencia: No se encontraron registros para la competencia '{competition_id}'")
    else:
        print(f"[OK] Acceso confirmado a la competencia '{competition_id}' ({len(test_data)} registros encontrados)")
except requests.exceptions.RequestException as e:
    print(f"Error al acceder a la competencia '{competition_id}': {e}")
    print("Verifica que el competition_id sea correcto y que tengas conexión a internet.")
    sys.exit(1)

# ---------- 1. Descargar registros ----------
print("Descargando registros de la competencia...")
resp = requests.get(REGS_URL)
resp.raise_for_status()
registrations = resp.json()
print(f"Registros encontrados: {len(registrations)}")

# ---------- 2. Info de competidores ----------
competitors = []
for r in registrations:
    user_id = r.get("user_id")
    events = r.get("event_ids", []) or []
    ru = requests.get(USER_URL.format(user_id))
    if ru.status_code != 200:
        continue
    user = ru.json().get("user", {})
    competitors.append({
        "user_id": user_id,
        "name": user.get("name"),
        "wca_id": user.get("wca_id"),
        "country": user.get("country_iso2"),
        "events": events
    })
    time.sleep(0.08)

# Ordenar alfabéticamente por nombre (ignorando tildes)
competitors.sort(key=lambda c: unicodedata.normalize("NFD", (c["name"] or "").lower()))
print(f"[OK] Competidores ordenados: {[c['name'] for c in competitors[:5]]}...")

df_competitors = pd.DataFrame(competitors)
# df_competitors.to_csv("competencia_competitors.csv", index=False, encoding="utf-8-sig")
# print("[OK] competencia_competitors.csv guardado.")

# ---------- 3. Descargar PRs ----------
prs_rows = []
for comp in competitors:
    wid = comp["wca_id"]
    if not wid:
        continue
    rp = requests.get(PERSON_URL.format(wid))
    if rp.status_code != 200:
        continue
    pjson = rp.json()
    personal = pjson.get("personal_records", {})
    for ev in comp["events"]:
        rec = personal.get(ev, {})
        if not rec:
            continue
        prs_rows.append({
            "wca_id": wid,
            "name": comp["name"],
            "event": ev,
            "single": rec.get("single", {}).get("best"),
            "average": rec.get("average", {}).get("best")
        })
    time.sleep(0.08)

df_prs = pd.DataFrame(prs_rows)
# df_prs.to_csv("competencia_prs.csv", index=False, encoding="utf-8-sig")
# print("[OK] competencia_prs.csv guardado.")

# ---------- 4. Formatear resultados ----------

def format_cs(cs):
    if pd.isna(cs) or cs == "" or cs == 0:
        return ""
    cs = int(cs)

    sec = cs // 100
    cs_rem = cs % 100
    mins = sec // 60
    sec = sec % 60

    if mins > 0:
        return f"{mins}:{sec:02d}.{cs_rem:02d}"
    else:
        return f"{sec}.{cs_rem:02d}"


def format_mbf(val):
    """Formatea el tiempo de 3x3 Multi-Blind"""
    if pd.isna(val) or val == "" or val == 0:
        return ""
    val = int(val)
    val_str = str(val)
    
    # El formato WCA para 333mbf:
    # El formato "new" es: 0DDTTTTTMM (10 dígitos)
    # difference = 99 - DD
    # timeInSeconds = TTTTT (5 dígitos)
    # missed = MM
    # solved = difference + missed
    # attempted = solved + missed
    
    # Pero la API puede devolver valores con diferente longitud
    # Ajustar según la longitud
    if len(val_str) == 9:
        # Formato sin el 0 inicial
        DD = int(val_str[:2])
        TTTTT = int(val_str[2:7])
        MM = int(val_str[7:])
    elif len(val_str) == 10:
        DD = int(val_str[1:3])
        TTTTT = int(val_str[3:8])
        MM = int(val_str[8:])
    else:
        #other lengths - try to handle generically
        DD = int(val_str[:2])
        MM = int(val_str[-2:])
        TTTTT = int(val_str[2:-2])
    
    difference = 99 - DD
    missed = MM
    solved = difference + missed
    attempted = solved + missed
    time_seconds = TTTTT
    
    if time_seconds == 99999:
        if solved > 0:
            return f"{solved}/{attempted}"
        else:
            return ""
    
    mins = time_seconds // 60
    secs = time_seconds % 60
    
    if mins > 0:
        time_str = f"{mins}:{secs:02d}"
    else:
        time_str = f"{secs}"
    
    if solved > 0:
        return f"{solved}/{attempted} {time_str}"
    else:
        return ""
    val = int(val)
    val_str = str(val)
    
    # El formato de WCA puede ser "old" (9 dígitos) o "new" (10 dígitos)
    # Primero intentamos con formato "old": 1SSAATTTTT
    # solved = 99 - SS
    # attempted = AA
    # timeInSeconds = TTTTT
    
    if len(val_str) == 9:
        # Formato old sin el 1 inicial o con otro dígito
        # Intentamos parsear directamente
        # Estructura: SSAATTTTT (9 dígitos)
        if len(val_str) >= 9:
            try:
                # Para valores como 970075800:
                # Podría ser: SS=97, AA=00, TTTTT=75800
                SS = int(val_str[0:2])
                AA = int(val_str[2:4])
                TTTTT = int(val_str[4:9])
                
                solved = 99 - SS
                attempted = AA
                time_seconds = TTTTT
                
                # Verificar si los valores son razonables
                # attempted debe ser <= 99 y solved <= attempted
                if attempted > 0 and attempted <= 99 and solved <= attempted:
                    if time_seconds <= 99999:
                        mins = time_seconds // 60
                        secs = time_seconds % 60
                        
                        if mins > 0:
                            time_str = f"{mins}:{secs:02d}"
                        else:
                            time_str = f"{secs}"
                        
                        if solved > 0:
                            return f"{solved}/{attempted} {time_str}"
            except:
                pass
    
    # Si el formato old no funcionó, intentamos con formato new: 0DDTTTTTMM
    val_str = val_str.zfill(10)
    
    DD = int(val_str[:2])
    TTTTT = int(val_str[2:7])
    MM = int(val_str[7:])
    
    difference = 99 - DD
    missed = MM
    solved = difference + missed
    attempted = solved + missed
    time_seconds = TTTTT
    
    if time_seconds == 99999:
        if solved > 0:
            return f"{solved}/{attempted}"
        else:
            return ""
    
    time_seconds = TTTTT
    mins = time_seconds // 60
    secs = time_seconds % 60
    
    if mins > 0:
        time_str = f"{mins}:{secs:02d}"
    else:
        time_str = f"{secs}"
    
    if solved > 0:
        return f"{solved}/{attempted} {time_str}"
    else:
        return ""


# 🔴 NORMALIZACIÓN REAL DE FEWEST MOVES
def normalize_fm(val):
    if pd.isna(val) or val == "" or val == 0:
        return None

    val = float(val)

    # Caso 0.27 → 27
    if val < 1:
        return val * 100

    # Caso 2700 → 27
    if val >= 100:
        return val / 100

    # Caso 27 → 27
    return val


def format_fm(val, is_average=False):
    moves = normalize_fm(val)
    if moves is None:
        return ""

    if is_average:
        return f"{moves:.2f}".rstrip("0").rstrip(".")
    else:
        return str(int(round(moves)))


def format_by_event(row, field):
    if row["event"] == "333fm":
        return format_fm(row[field], is_average=(field == "average"))
    elif row["event"] == "333mbf":
        return format_mbf(row[field])
    else:
        return format_cs(row[field])


df_prs["single_f"] = df_prs.apply(lambda r: format_by_event(r, "single"), axis=1)
df_prs["average_f"] = df_prs.apply(lambda r: format_by_event(r, "average"), axis=1)


# ---------- 5. Dimensiones plantilla ----------
tpl_reader = PdfReader(TEMPLATE)
tpl_page = tpl_reader.pages[0]
TPL_W = float(tpl_page.mediabox.width)
TPL_H = float(tpl_page.mediabox.height)

# ---------- 6. Nombres oficiales ----------
event_names = {
    "222": "2x2", "333": "3x3", "444": "4x4", "555": "5x5", "666": "6x6", "777": "7x7",
    "333bf": "3x3 Blindfolded", "333fm": "3x3 Fewest Moves", "333oh": "3x3 One-Handed",
    "clock": "Clock", "minx": "Megaminx", "pyram": "Pyraminx", "skewb": "Skewb",
    "sq1": "Square-1", "444bf": "4x4 Blindfolded", "555bf": "5x5 Blindfolded",
    "333mbf": "3x3 Multi-Blind"
}


# ---------- 7. Crear gafetes individuales ----------
print("Generando gafetes individuales usando la plantilla...")

# Carpeta temporal para gafetes individuales (se elimina al final)
TEMP_DIR = "_gafetes_temp"
os.makedirs(TEMP_DIR, exist_ok=True)

# Caché de banderas: descarga cada país solo una vez
from io import BytesIO
from reportlab.lib.utils import ImageReader
flag_cache = {}

def get_flag(country_code):
    if not country_code or len(country_code) != 2:
        return None
    cc = country_code.lower()
    if cc in flag_cache:
        return flag_cache[cc]
    try:
        resp = requests.get(f"https://flagcdn.com/w80/{cc}.png", timeout=5)
        if resp.status_code == 200:
            flag_cache[cc] = ImageReader(BytesIO(resp.content))
            return flag_cache[cc]
    except:
        pass
    flag_cache[cc] = None
    return None

final_gafetes = []
for idx, comp in enumerate(competitors):
    wid = comp["wca_id"]
    # Get country code for flag
    country_code = comp.get("country")
    competitor_name = comp["name"] or str(comp["user_id"])
    
    # Obtener bandera desde caché (descarga solo si no está cacheada)
    flag_image = get_flag(country_code)
    
    dfc = df_prs[df_prs["wca_id"] == wid] if wid else pd.DataFrame()

    overlay = os.path.join(TEMP_DIR, f"overlay_{idx:03d}.pdf")
    c = canvas.Canvas(overlay, pagesize=(TPL_W, TPL_H))

    # ======================
    # Ajustes de posiciones
    # ======================
    left_margin = 0.75 * cm
    box_top = TPL_H - 5.5*cm
    line_spacing = 11

    # ===== Nombre del competidor =====
    c.setFont("Helvetica-Bold", 12)
    if flag_image:
        # Draw flag to the LEFT of the name
        flag_width = 0.8 * cm
        flag_height = 0.53 * cm  # Maintain aspect ratio
        center_x = TPL_W / 2
        # Calculate position: flag to the left, name centered
        name_width = c.stringWidth(competitor_name, "Helvetica-Bold", 12)
        total_width = flag_width + 0.3 * cm + name_width
        start_x = center_x - total_width / 2
        
        # Draw flag first (to the left)
        c.drawImage(flag_image, start_x, TPL_H - 4.2*cm, width=flag_width, height=flag_height, mask='auto')
        # Draw name after flag
        c.drawString(start_x + flag_width + 0.3*cm, TPL_H - 4.1*cm, competitor_name)
    else:
        # No flag, just center the name
        c.drawCentredString(TPL_W/2, TPL_H - 4.1*cm, competitor_name)

    # ----- Records Personales -----
    c.setFont("Helvetica-Bold", 10)
    title = "Records Personales (Single,Average):"
    title_width = c.stringWidth(title, "Helvetica-Bold", 10)
    title_x = (TPL_W - title_width) / 2
    c.drawString(title_x, box_top, title)

    # Calcular distribución óptima de columnas
    num_events = len(dfc)
    if num_events <= 6:
        num_cols = 1
    elif num_events <= 12:
        num_cols = 2
    else:
        num_cols = 2
    
    font_size = 8
    c.setFont("Helvetica", font_size)

    col_gap = 0.4 * cm
    usable_width = TPL_W - 2 * left_margin
    
    if num_cols == 1:
        # Centrar la única columna
        # Usar aproximadamente 60% del ancho disponible para la columna
        col_width = usable_width * 0.6
        # Centrar la columna en el espacio disponible
        total_col_width = col_width
        x_positions = [(usable_width - total_col_width) / 2 + left_margin]
    else:
        col_width = (usable_width - col_gap) / num_cols
        x_positions = [left_margin + i * (col_width + col_gap) for i in range(num_cols)]
    
    line_spacing = 10
    y_start = box_top - 2.0 * line_spacing

    events_list = dfc.to_dict('records')
    
    for i, ev_data in enumerate(events_list):
        if num_cols == 1:
            col = 0
            row = i
        else:
            # Distribuir evenly: si hay 8 eventos, 4 y 4
            # Si hay 7 eventos, 4 y 3
            split = num_events // 2
            col = 0 if i < split else 1
            row = i if i < split else i - split
        
        ev = ev_data["event"]
        ev_name = event_names.get(ev, ev)
        s = ev_data["single_f"]
        a = ev_data["average_f"]
        line = f"{ev_name}: {s}" + (f" / {a}" if a else "")
        
        x = x_positions[col]
        y = y_start - row * line_spacing
        
        if y < 2 * cm:
            break
        
        c.drawString(x, y, line)

    c.save()
    # Superponer overlay en plantilla
    tpl_r = PdfReader(TEMPLATE)
    ov_r = PdfReader(overlay)
    base_page = tpl_r.pages[0]
    base_page.merge_page(ov_r.pages[0])
    writer = PdfWriter()
    writer.add_page(base_page)

    final_name = os.path.join(TEMP_DIR, f"gafete_final_{idx:03d}.pdf")
    with open(final_name, "wb") as fh:
        writer.write(fh)

    os.remove(overlay)
    final_gafetes.append(final_name)

print(f"[OK] Gafetes individuales creados: {len(final_gafetes)}")


# ---------- 7b. Gafetes de reserva (relleno de páginas incompletas) ----------
GAFETES_POR_PAGINA = 6
total = len(final_gafetes)
resto = total % GAFETES_POR_PAGINA

print("\n" + "="*50)
print(" GAFETES DE RESERVA ")
print("="*50)

def crear_gafete_en_blanco(idx_reserva):
    """Genera un gafete en blanco (solo plantilla, sin texto) para reserva."""
    tpl_r = PdfReader(TEMPLATE)
    writer = PdfWriter()
    writer.add_page(tpl_r.pages[0])
    nombre = os.path.join(TEMP_DIR, f"gafete_reserva_{idx_reserva}.pdf")
    with open(nombre, "wb") as fh:
        writer.write(fh)
    return nombre

gafetes_reserva_creados = []

if resto == 0:
    # Caso 1: múltiplo exacto de 6 → preguntar si quiere página extra de reserva
    print(f"Los {total} competidores llenan exactamente {total // GAFETES_POR_PAGINA} página(s) (sin espacios sobrantes).")
    print(f"¿Desea agregar una página extra con {GAFETES_POR_PAGINA} gafetes en blanco de reserva?")
    print("  [1] Sí, agregar página de reserva")
    print("  [2] No, el PDF queda exacto")
    opcion = input("Seleccione una opción (1/2): ").strip()
    if opcion == "1":
        for i in range(GAFETES_POR_PAGINA):
            gafetes_reserva_creados.append(crear_gafete_en_blanco(i))
        print(f"[OK] Se agregarán {GAFETES_POR_PAGINA} gafetes de reserva en una página extra.")
    else:
        print("[OK] Sin gafetes de reserva. El PDF quedará exacto.")
else:
    # Caso 2: última página incompleta → preguntar si quiere rellenar los huecos
    faltantes = GAFETES_POR_PAGINA - resto
    paginas_completas = total // GAFETES_POR_PAGINA
    print(f"Hay {total} competidores → {paginas_completas} página(s) completa(s) + 1 página con solo {resto} gafete(s).")
    print(f"Faltan {faltantes} gafete(s) para completar la última página.")
    print(f"¿Qué desea hacer con los {faltantes} espacio(s) sobrante(s)?")
    print(f"  [1] Rellenar con {faltantes} gafete(s) de reserva (recomendado)")
    print(f"  [2] Dejar los espacios en blanco")
    opcion = input("Seleccione una opción (1/2): ").strip()
    if opcion == "1":
        for i in range(faltantes):
            gafetes_reserva_creados.append(crear_gafete_en_blanco(i))
        print(f"[OK] Se agregarán {faltantes} gafete(s) de reserva para completar la última página.")
    else:
        print("[OK] Los espacios sobrantes quedarán vacíos.")

# Agregar gafetes de reserva al final de la lista
final_gafetes.extend(gafetes_reserva_creados)

if gafetes_reserva_creados:
    print(f"[OK] Total de gafetes a imprimir: {len(final_gafetes)} ({len(gafetes_reserva_creados)} de reserva)")
print("="*50 + "\n")


# ---------- 8. Combinar en tamaño Carta (6 por página, 2x3, rotados, con márgenes mínimos) ----------
print("Combinando gafetes en tamaño Carta (6 por página, márgenes mínimos)...")

# Tamaño carta
PAGE_W = 21.59 * cm   # 8.5 pulgadas
PAGE_H = 27.94 * cm   # 11 pulgadas

# Márgenes reducidos y separación mínima
MARGIN_LEFT = 0.4 * cm
MARGIN_TOP = 0.4 * cm
GAP_X = 0.5 * cm
GAP_Y = 0.5 * cm

# Escala ajustada para llenar más la hoja
SCALE = 0.97
GAF_W = TPL_H * SCALE
GAF_H = TPL_W * SCALE

# Posiciones (2 columnas x 3 filas)
NUM_COLS = 2
NUM_ROWS = 3
x_positions = [MARGIN_LEFT, MARGIN_LEFT + GAF_W + GAP_X]
y_positions = [
    PAGE_H - MARGIN_TOP - GAF_H,
    PAGE_H - MARGIN_TOP - 2*GAF_H - GAP_Y,
    PAGE_H - MARGIN_TOP - 3*GAF_H - 2*GAP_Y
]

# Crear PDF final
doc = fitz.open()

for i in range(0, len(final_gafetes), 6):
    page = doc.new_page(width=PAGE_W, height=PAGE_H)
    group = final_gafetes[i:i + 6]

    for j, gafpath in enumerate(group):
        col = j % NUM_COLS
        row = j // NUM_COLS

        x = x_positions[col]
        y = y_positions[row]
        rect = fitz.Rect(x, y, x + GAF_W, y + GAF_H)

        gaf_doc = fitz.open(gafpath)
        # Mantener alta calidad y orientación correcta (rotar 90°)
        page.show_pdf_page(rect, gaf_doc, 0, rotate=90)

        gaf_doc.close()

if os.path.exists(OUTPUT_PDF):
    try:
        os.remove(OUTPUT_PDF)
    except:
        pass
import tempfile
import shutil

# Save to temp file first, then move
temp_file = OUTPUT_PDF + ".temp"
doc.save(temp_file)
doc.close()

# Remove old file and rename temp
if os.path.exists(OUTPUT_PDF):
    try:
        os.remove(OUTPUT_PDF)
    except:
        pass

shutil.move(temp_file, OUTPUT_PDF)
print(f"[OK] PDF final listo y ajustado: {OUTPUT_PDF}")




# ---------- 9. Limpiar temporales ----------
import shutil as _shutil
try:
    _shutil.rmtree(TEMP_DIR)
except:
    pass

print("[OK] Archivos temporales eliminados. Solo quedan la plantilla y el PDF final.")